### ISSUE TITLE
Import notes as well

### ISSUE THREAD

**Issue by SalieriC** [TarkanAl-Kazily/one-page-parser#2]
This module is really great to very quickly set something up.
I would appreciate - if that is possible - to have the notes imported as well.

**Comment by SalieriC** [comment]
If the .json doesn't include them maybe having a way to import the saved (not exported) .png seperately and create a Journal Entry with just the .png in a Folder called "One Page Dungeon", the name of the scene and setting it up as the Journal Entry of the Scene:  

![image](https://user-images.githubusercontent.com/1230041/109805648-03d6ae80-7c24-11eb-9814-ef652972b66a.png)  
![image](https://user-images.githubusercontent.com/1230041/109805770-22d54080-7c24-11eb-836c-7d47dcfbf58e.png)

This file ficker could also be optional in case one wouldn't want that.

**Comment by surged20** [comment]
The json includes the notes so ideally it would import a folder with the title of the map, the summary as a journal, and then each note as a separate journal entry in the folder.

The notes also have coordinates so an additional feature might be to place a map note/pin corresponding to each note journal entry on the imported map. Making use of the Automatic Journal Icon Numbers module here would generate a matching map note icon automatically.

**Comment by SalieriC** [comment]
While I like the sound of that, this could flood the Journal with pretty short notes. Maybe having one JournalEntry per map and pinning them to the canvas at the appropriate place and then giving the pins themselves numbers so that the user knows for wich number to look in the JournalEntry would be better to decrease the overall number of JournalEntries with extended usage of the module?

**Comment by surged20** [comment]
That's just my preference of how I prepare my maps so I have spatial reminders as to what's next. I don't think it's flooding the Journal as it's contained in a per map folder anyway (if named for the map/scene). But, to your point, if it's a single journal entry with each area in a separate section, then one can replicate what I described with the Furnace module's journal splitter (that's what I use on lengthy multi-area journal entries anyway) and drag-and-dropped for the map notes. I just noticed that all the info is available to completely automate this..which is interesting.

In any case, it can be an option too...doesn't have to be one size fits all. :smile:

**Comment by farling42** [comment]
This can be done with the following code (in 0.8.6):
`            await newScene.createEmbeddedDocuments("Note", info["notes"].map(d => {
				const txt = d["text"];
				const pos = txt.indexOf(' ', txt.length/2);
				
                return {
                    x : d["pos"]["x"] * g - minvals[0] + x_offset,
                    y : d["pos"]["y"] * g - minvals[1] + y_offset,
                    text: txt.slice(0,pos) + '\n' + txt.slice(pos),
                    iconTint: "#00FF00",
                    textColor: "#00FF00",
                };
            }), {noHook: false});`

**Comment by TarkanAl-Kazily** [comment]
Introduced @farling42's suggestion in 0d1604deaf96b3fd2be86ac0682998ffcc44c64a - totally could have been a PR :wink: 
Thanks for the input, and sorry for the delay.
