### ISSUE TITLE
Always Asks to Update Manifest URL

### ISSUE THREAD

**Issue by Armandeus66** [TarkanAl-Kazily/one-page-parser#7]
This module (0.5.1) always asks to update the manifest URL when a module update is attempted. Updating the URL by selecting YES does not stop it from asking again the next time. Uninstalling the module and reinstalling does not fix the issue.
![1pp](https://user-images.githubusercontent.com/59499015/133009801-9218c8ba-7800-4460-8b79-fa8faf382c53.JPG)

**Comment by HippyCraig** [comment]
I am seseing the same thing. if there is any testing I can do to help with this let me know

**Comment by TarkanAl-Kazily** [comment]
I've updated the module.json as part of making a release for Foundry VTT version 10. This issue should be gone now.

**Comment by HippyCraig** [comment]
Thanks I tested on v10 and its not contstantly loading that dialog on update mods.

**Comment by Armandeus66** [comment]
It asks me every time the module is updated. It asked me again today.
![Screenshot 2022-10-15 080017](https://user-images.githubusercontent.com/59499015/195955691-58e25750-0a23-4577-9835-3906ea413fb0.png)
